# syntax=docker/dockerfile:1

FROM node:17.8.0

ENV NODE_ENV=development
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn install

# add app
# COPY . ./

# start app
CMD ["yarn", "start"]
